import * as React from "react";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Image from "next/image";

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased min-h-screen w-full`}
      >
        <header>
          {/* header desktop */}
          <div className="hidden md:block">
            <div className="bg-[#111] w-full min-h-[12vh] flex overflow-hidden">
              {/* logo */}
              <div className="px-[5vw]">
                <Image
                  src="/images/logoLong.svg"
                  alt="Logo"
                  width={100}
                  height={100}
                  className="h-full min-w-[15vw] w-[10vw] mx-auto invert"
                />
              </div>
              {/* navegação */}
              <nav className="w-full flex">
                <ul className="flex gap-[5vw] px-[2.5vw] items-center justify-evenly w-full">
                  <li>
                    <a className="text-[#fff] text-[clamp(1rem, 2vw, 2rem)] hover:text-red-500 transition-colors duration-250">
                      Serviços
                    </a>
                  </li>
                  <li>
                    <a className="text-[#fff] text-[clamp(1rem, 2vw, 2rem)] hover:text-red-500 transition-colors duration-250">
                      Projetos
                    </a>
                  </li>
                  <li>
                    <a className="text-[#fff] text-[clamp(1rem, 2vw, 2rem)] hover:text-red-500 transition-colors duration-250">
                      Contato
                    </a>
                  </li>
                  <li>
                    <a className="text-[#fff] text-[clamp(1rem, 2vw, 2rem)] hover:text-red-500 transition-colors duration-250">
                      Carreiras
                    </a>
                  </li>
                  <li>
                    <a className="text-[#fff] text-[clamp(1rem, 2vw, 2rem)] hover:text-red-500 transition-colors duration-250">
                      Sobre
                    </a>
                  </li>
                </ul>

                {/* botoes de login e cadastro */}
                <div className="flex gap-[5vw] px-[5vw] items-center justify-evenly">
                  <button className="btn rounded-xl bg-[#fff] text-[#000] ${montserrat.className}">
                    Login
                  </button>
                  <button className="btn rounded-xl bg-[#fff] text-[#000] ${montserrat.className}">
                    Cadastro
                  </button>
                </div>
              </nav>
            </div>
          </div>

          <div className="block md:hidden">
            <div className="w-full bg-[#111] min-h-[12vh] flex items-center">
              {/* logo */}
              <div className="px-[5vw]">
                <Image
                  src="/images/logoShort.svg"
                  alt="Logo"
                  width={100}
                  height={100}
                  className="h-full w-auto mx-auto invert"
                />
              </div>

              <nav>
                {/* botoes no extremo direito da tela */}
                <div className="flex gap-[5vw] px-[5vw] items-center justify-evenly">
                  <button className="btn rounded-xl bg-[#fff] text-[#000] ${montserrat.className}">
                    Login
                  </button>
                  <button className="btn rounded-xl bg-[#fff] text-[#000] ${montserrat.className}">
                    Cadastro
                  </button>
                </div>
              </nav>
            </div>
          </div>
        </header>
        {children}
        <footer>{/*  */}</footer>
      </body>
    </html>
  );
}
