import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <header>
          <div className="bg-[#111] w-full min-h-[12vh] flex">
            {/* logo */}
            <div className="px-[5vw]">
              <Image
                src="/images/logoLong.svg"
                alt="Logo"
                width={100}
                height={100}
                className="h-full w-[15vw] mx-auto invert"
              />
            </div>

            {/* navegação */}

            <nav className="w-full flex items-">
              <ul className="flex gap-[5vw] px-[5vw] items-center justify-evenly w-full">
                <li>
                  <a className="text-[#fff]">Serviços</a>
                </li>
                <li>
                  <a className="text-[#fff]">Projetos</a>
                </li>
                <li>
                  <a className="text-[#fff]">Contato</a>
                </li>
                <li>
                  <a className="text-[#fff]">Carreiras</a>
                </li>
                <li>
                  <a className="text-[#fff]">Quem Somos</a>
                </li>
              </ul>

              {/* botoes de login e cadastro */}
              <div className="flex gap-[5vw] px-[5vw] items-center justify-evenly">
                <button className="bg-[#fff]">Login</button>
                <button className="bg-[#fff]">Cadastro</button>
              </div>
            </nav>
          </div>
        </header>
        {children}
        <footer>{/*  */}</footer>
      </body>
    </html>
  );
}
